"""
Django settings for your project.

Generated by 'django-admin startproject' using Django X.X.X.
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------------------------------------
# 1. CORE DJANGO SETTINGS & SECURITY
# ----------------------------------------------------------------------

SECRET_KEY = os.getenv('SECRET_KEY', 'default-insecure-key-for-local')

# SECURITY FIXES FOR RAILWAY DEPLOYMENT
# Replace 'your-railway-domain.up.railway.app' with your actual domain
# The '*' allows all Railway subdomains (e.g., in previews)
ALLOWED_HOSTS = [
    os.getenv('RENDER_EXTERNAL_HOSTNAME'), # For Render (just in case)
    '127.0.0.1', 
    'localhost',
    '.railway.app', # Allows all subdomains on Railway
    # Add your custom production domain here if applicable
    # 'your-custom-domain.com'
] 

# Set DEBUG based on environment variable (Crucial for production security)
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'corsheaders',              # Required for API security checks
    'rest_framework',           # Django REST Framework
    'django_cleanup.apps.CleanupConfig', # Cleans up old files

    # Your apps
    'accounts',
    # Add other apps here...
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Must be high up
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ----------------------------------------------------------------------
# 2. DATABASE & STATIC/MEDIA FILES
# ----------------------------------------------------------------------

# Database configuration (using environment variables)
# Uses SQLite locally, but you must configure a PostgreSQL/MySQL URL for Railway.
# Example: DATABASES['default'] = dj_database_url.config(default=os.getenv('DATABASE_URL'))
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# NOTE: If you use a remote database, you must install 'psycopg2' or similar 
# and use 'dj-database-url' to parse the DATABASE_URL environment variable.


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media Files (User Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise Configuration (For serving static files in production)
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ----------------------------------------------------------------------
# 3. AUTHENTICATION & VALIDATION
# ----------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Redirect URLs
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# ----------------------------------------------------------------------
# 4. INTERNATIONALIZATION & TIME
# ----------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila' # Set to your local timezone or UTC
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------------------------
# 5. API / EMAIL / CORS / CSRF SETTINGS
# ----------------------------------------------------------------------

# CORS/CSRF Configuration (CRITICAL for API and web form interaction)

# Trust the Railway proxy to correctly identify HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') 

# CRITICAL CSRF Fix for deployment (Add your Railway domain)
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://127.0.0.1', # For local testing
    # Add your specific app domain if needed:
    # 'https://your-app-name-production.up.railway.app'
]

# CORS settings for the mobile app API
# Adjust these to your mobile app's domain(s)
CORS_ALLOW_ALL_ORIGINS = True # Be cautious with this in production
# OR use a whitelist:
# CORS_ALLOWED_ORIGINS = [
#     "capacitor://localhost",
#     "ionic://localhost",
#     "http://localhost",
#     "http://localhost:8100", # Ionic/Capacitor development URL
# ]
# CORS_ALLOW_CREDENTIALS = True


# Email Backend (Necessary for OTP sending)
# Use environment variables for production security
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ----------------------------------------------------------------------
# 6. PRODUCTION SECURITY CHECKLIST (Set these to True in production)
# ----------------------------------------------------------------------

if not DEBUG:
    # Enforce HTTPS on cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Enforce redirects to HTTPS
    # SECURE_SSL_REDIRECT = True # Use with caution if Railway handles SSL entirely

    # HSTS settings (Recommended for A-rated security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# End of settings.py